variables:
  MSBUILD_CONCURRENCY: 4
  VSWHERE_PATH: '%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe'
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\msbuild.exe'
  XUNIT_PATH: 'C:\Tools\XUnit\net472\xunit.console.exe'
  ARTIFACTS_PATH: '.\ExperimentalProject\bin\Release' 
  ARTIFACT: 'WidgetBoard'


.before_msbuild: &enter_vsdevshell
  before_script:
    - '$vsWherePath = [System.Environment]::ExpandEnvironmentVariables($env:VSWHERE_PATH)'
    - '& $vsWherePath -latest -format value -property installationPath -products Microsoft.VisualStudio.Product.BuildTools | Tee-Object -Variable visualStudioPath'
    - 'Join-Path "$visualStudioPath" "\Common7\Tools\Microsoft.VisualStudio.DevShell.dll" | Import-Module'
    - 'Enter-VsDevShell -VsInstallPath:"$visualStudioPath" -SkipAutomaticLocation'

stages:
  - build

build_job:
  stage: build 
  tags:
    - windows
    - netframework 
  only: 
    - branches
  script: 
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /m:$env:MSBUILD_CONCURRENCY /nr:false /clp:ErrorsOnly'
    - 'New-Item -ItemType Directory -Path .\flattened_artifacts'
    - 'Copy-Item -Path .\ExperimentalProject\bin\Release\* -Destination .\flattened_artifacts\ -Recurse'
  artifacts: 
    expire_in: 6 mos 
    expose_as: '$env:ARTIFACT' 
    name: '$env:ARTIFACT' 
    paths: 
      - '.\flattened_artifacts\'
